version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: diff
    versions:
    - 5.0.0
  - dependency-name: source-map
    versions:
    - 0.7.3
