services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/backdir
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5050:5050"
  frontend:
    build:
      context: ./stlstuff
      dockerfile: ./Dockerfile
    volumes:
      - ./stlstuff:/frontdir
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    links:
      - "backend:be"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

