services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/backdir
    ports:
      - "5050:5050"
  frontend:
    build:
      context: ./stlstuff
      dockerfile: ./Dockerfile
    volumes:
      - ./stlstuff:/frontdir
    ports:
      - "3000:3000"
    links:
      - "backend:be"

